const $=s=>document.querySelector(s),state={cases:[],detail:null,status:"",timeliness:""};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const identity=()=>({actor:$("#actor").value.trim(),role:$("#role").value,idempotencyKey:crypto.randomUUID()});
const localValue=v=>{const d=new Date(v),p=n=>String(n).padStart(2,"0");return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`};
async function api(path,options={}){const res=await fetch(path,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})}}),body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body.error?.message||`请求失败 ${res.status}`);return body}
function toast(message){const n=$("#toast");n.textContent=message;n.classList.add("show");setTimeout(()=>n.classList.remove("show"),2600)}
async function loadCases(){const q=new URLSearchParams();if(state.status)q.set("status",state.status);if(state.timeliness)q.set("timeliness",state.timeliness);const data=await api(`/api/v1/cases${q.size?`?${q}`:""}`);state.cases=data.items;renderList()}
function renderList(){const box=$("#case-list");box.innerHTML=state.cases.length?state.cases.map(c=>`<article class="case-card ${state.detail?.case.id===c.id?"active":""}" data-id="${esc(c.id)}"><strong>${esc(c.accessionCode)}</strong><span>${esc(c.speciesName)}</span><span>${esc(c.status)} · v${c.revision}</span></article>`).join(""):`<p>当前没有案卷</p>`;box.querySelectorAll(".case-card").forEach(n=>n.onclick=()=>openCase(n.dataset.id))}
async function openCase(id){state.detail=await api(`/api/v1/cases/${id}`);$("#empty").hidden=true;$("#detail").hidden=false;renderDetail();renderList()}
function renderDetail(){const c=state.detail.case,receiver=$("#role").value==="receiver";$("#case-code").textContent=c.accessionCode;$("#case-title").textContent=c.speciesName;$("#case-meta").textContent=`${c.collectionSite} · 采集 ${new Date(c.collectedAt).toLocaleString()} · 到库 ${new Date(c.receivedAt).toLocaleString()} · 负责人 ${c.owner} · 版本 ${c.revision}`;$("#case-status").textContent=c.status;$("#edit-case").hidden=!receiver||!["草稿","待抽样"].includes(c.status);$("#add-lot").hidden=!receiver||!["草稿","待抽样"].includes(c.status)||!!c.sampling;const order=["草稿","待抽样","检验中","整改中","待审核","已放行"],at=order.indexOf(c.status);document.querySelectorAll("#steps li").forEach((n,i)=>n.classList.toggle("done",i<=at));renderLots(c);renderTests(c);renderRelease(c)}
function renderLots(c){$("#lots").innerHTML=c.lots.length?c.lots.map(l=>`<div class="item"><div><strong>${esc(l.lotCode)}</strong><small>容器 ${esc(l.containerCode)} · ${l.seedCount} 粒 · 含水率 ${l.moisturePercent}% · ${esc(l.arrivalCondition)}</small></div><span>留样 ${l.reservedCount}</span></div>`).join(""):`<p>尚未登记种子批次。</p>`;const p=c.sampling;if(!p){$("#sampling").innerHTML=c.lots.length?`<button id="generate-sampling">按 SVR-2026.1 生成抽样方案</button>`:"";$("#generate-sampling")?.addEventListener("click",generateSampling);return}$("#sampling").innerHTML=`<div class="notice"><strong>抽样方案 ${esc(p.ruleVersion)}${p.confirmedAt?"（已冻结）":""}</strong>${p.items.map(i=>`<div class="balance"><b>${esc(i.lotCode)}</b><span>计划 ${i.plannedCount}</span><span>实际 ${i.actualCount||"待确认"}</span><span>留样 ${i.reservedCount}</span><span>可用余量 ${p.confirmedAt?i.availableCount:"待确认"}</span>${i.deviationReason?`<small>偏差：${esc(i.deviationReason)}</small>`:""}</div>`).join("")}${!p.confirmedAt&&$("#role").value==="receiver"?'<button id="confirm-sampling">核对并确认实际取样</button>':p.confirmedAt?`<small>由 ${esc(p.confirmedBy)} 于 ${new Date(p.confirmedAt).toLocaleString()} 确认</small>`:""}</div>`;$("#confirm-sampling")?.addEventListener("click",confirmSampling)}
function matrixConclusion(cell){if(cell.state==="missing")return "缺项";const a=cell.assessment;return `${cell.state==="pass"?"通过":"异常"} · ${esc(a.conclusion)} · 发芽率 ${a.passRate.toFixed(2)}% / 污染率 ${a.contaminationRate.toFixed(2)}%`}
function renderTests(c){const cells=state.detail.testMatrix||[];$("#tests").innerHTML=cells.length?`<div class="matrix">${cells.map(cell=>`<label class="matrix-cell ${cell.state}">${cell.state==="missing"&&$("#role").value==="tester"?`<input type="checkbox" data-missing="${esc(cell.lotId)}|${cell.testType}">`:""}<strong>${esc(cell.lotCode)} · ${cell.testType==="germination"?"发芽活力":"污染筛查"}</strong><small>${matrixConclusion(cell)}</small></label>`).join("")}</div>`:"<p>确认抽样后将生成批次 × 检验类型矩阵。</p>";$("#add-test").hidden=$("#role").value!=="tester"||!["检验中","整改中"].includes(c.status)||!cells.some(x=>x.state==="missing");$("#findings").innerHTML=c.findings.map(f=>`<div class="finding ${esc(f.status)}"><div class="finding-head"><strong>${esc(f.category)}</strong><span class="timing ${f.timeliness==="逾期"?"overdue":""}">${esc(f.timeliness)}</span></div><small>状态 ${esc(f.status)} · 负责人 ${esc(f.assignee||"未指派")} · 截止 ${f.dueAt?new Date(f.dueAt).toLocaleString():"未设置"}</small><div class="evidence-list">${(f.evidenceLedger||[]).map(e=>`<p><b>${esc(e.submittedBy)}</b> ${new Date(e.submittedAt).toLocaleString()}<br>${esc(e.description)}<br><code>${esc(e.contentDigest)}</code></p>`).join("")||"<p>尚无处置证据</p>"}</div>${findingActions(c,f)}</div>`).join("");document.querySelectorAll("[data-assign]").forEach(n=>n.onclick=()=>assignFinding(n.dataset.assign));document.querySelectorAll("[data-evidence]").forEach(n=>n.onclick=()=>addEvidence(n.dataset.evidence));document.querySelectorAll("[data-retest]").forEach(n=>n.onclick=()=>recordRetest(n.dataset.retest));document.querySelectorAll("[data-remediate]").forEach(n=>n.onclick=()=>remediate(n.dataset.remediate));document.querySelectorAll("[data-close]").forEach(n=>n.onclick=()=>closeFinding(n.dataset.close))}
function findingActions(c,f){if($("#role").value!=="tester")return "";if(f.status==="open")return `<div class="button-row"><button data-assign="${esc(f.id)}">指派与期限</button><button data-evidence="${esc(f.id)}">追加证据</button><button data-retest="${esc(f.id)}">记录复验</button><button data-remediate="${esc(f.id)}">提交整改</button></div>`;if(f.status==="remediated")return `<button data-close="${esc(f.id)}">独立复核关闭</button>`;return ""}
function renderRelease(c){$("#approve").hidden=c.status!=="待审核"||$("#role").value!=="reviewer";$("#certificate").innerHTML=c.certificate?`<div class="certificate"><strong>保藏放行凭据 #${c.certificate.serialNumber}</strong><p>签发人 ${esc(c.certificate.approvedBy)} · ${new Date(c.certificate.issuedAt).toLocaleString()} · 案卷版本 v${c.certificate.caseRevision}</p><code>${esc(c.certificate.manifestDigest)}</code><p><button id="verify-current">逐项核验并对照清单</button></p></div>`:`<p>审核冻结后将签发只追加保藏放行凭据。</p>`;$("#verify-current")?.addEventListener("click",()=>verifyCredential("serialNumber",c.certificate.serialNumber));$("#timeline").innerHTML=state.detail.timeline.map(e=>`<div class="event"><strong>${esc(e.action)}</strong><small> ${esc(e.actor)} · v${e.caseRevision} · ${new Date(e.at).toLocaleString()}</small></div>`).join("")}
function fields(items){return items.map(x=>`<label class="field">${esc(x.label)}${x.type==="select"?`<select name="${esc(x.name)}">${x.options.map(o=>`<option value="${esc(o[0])}">${esc(o[1])}</option>`).join("")}</select>`:x.type==="textarea"?`<textarea name="${esc(x.name)}" ${x.required===false?"":"required"}>${esc(x.value||"")}</textarea>`:`<input name="${esc(x.name)}" type="${esc(x.type||"text")}" value="${esc(x.value??"")}" ${x.step?`step="${esc(x.step)}"`:""} ${x.required===false?"":"required"}>`}</label>`).join("")}
function modal(title,html,onSubmit){$("#dialog-title").textContent=title;$("#dialog-fields").innerHTML=html;const d=$("#dialog");d.showModal();$("#dialog-form").onsubmit=async e=>{e.preventDefault();try{await onSubmit(new FormData(e.target),e.target);d.close()}catch(err){toast(err.message)}}}
$("#dialog-close").onclick=$("#dialog-cancel").onclick=()=>$("#dialog").close();
$("#new-case").onclick=()=>modal("新建入藏案卷",fields([{name:"accessionCode",label:"案卷编号"},{name:"speciesName",label:"物种名称"},{name:"collectionSite",label:"采集地点"},{name:"collectedAt",label:"采集时间",type:"datetime-local"},{name:"receivedAt",label:"到库时间",type:"datetime-local"},{name:"owner",label:"负责人"}]),async fd=>{const d=Object.fromEntries(fd),c=await api("/api/v1/cases",{method:"POST",body:JSON.stringify({...d,...identity(),collectedAt:new Date(d.collectedAt),receivedAt:new Date(d.receivedAt)})});await loadCases();await openCase(c.id);toast("案卷已创建")});
$("#edit-case").onclick=()=>{const c=state.detail.case;modal("受控修订案卷基础资料",fields([{name:"speciesName",label:"物种名称",value:c.speciesName},{name:"collectionSite",label:"采集地点",value:c.collectionSite},{name:"collectedAt",label:"采集时间",type:"datetime-local",value:localValue(c.collectedAt)},{name:"receivedAt",label:"到库时间",type:"datetime-local",value:localValue(c.receivedAt)},{name:"owner",label:"负责人",value:c.owner}]),async fd=>{const d=Object.fromEntries(fd);await api(`/api/v1/cases/${c.id}/base-data`,{method:"PATCH",body:JSON.stringify({...d,...identity(),expectedRevision:c.revision,collectedAt:new Date(d.collectedAt),receivedAt:new Date(d.receivedAt)})});await openCase(c.id);await loadCases();toast("基础资料已修订并记录审计摘要")})};
function lotRow(i){return `<div class="batch-row" data-row><b>批次 ${i}</b><button type="button" data-remove>移除</button>${fields([{name:"lotCode",label:"批次编号"},{name:"containerCode",label:"容器编号"},{name:"seedCount",label:"种子数量",type:"number",value:200},{name:"moisturePercent",label:"含水率（%）",type:"number",step:"0.1",value:8},{name:"arrivalCondition",label:"到库外观",value:"完整、干燥"},{name:"reservedCount",label:"留样数量",type:"number",value:50}])}</div>`}
$("#add-lot").onclick=()=>{const c=state.detail.case;modal("种子批次原子批量登记",`<div id="lot-rows">${lotRow(1)}</div><button type="button" id="append-lot">＋ 增加一行</button>`,async(_,form)=>{const normalized=[...form.querySelectorAll("[data-row]")].map(row=>{const get=n=>row.querySelector(`[name="${n}"]`).value;return {lotCode:get("lotCode"),containerCode:get("containerCode"),seedCount:+get("seedCount"),moisturePercent:+get("moisturePercent"),arrivalCondition:get("arrivalCondition"),reservedCount:+get("reservedCount")}});await api(`/api/v1/cases/${c.id}/lots/batch`,{method:"POST",body:JSON.stringify({...identity(),expectedRevision:c.revision,items:normalized})});await openCase(c.id);await loadCases();toast(`${normalized.length}个批次已原子登记`)});$("#append-lot").onclick=()=>{$("#lot-rows").insertAdjacentHTML("beforeend",lotRow(document.querySelectorAll("[data-row]").length+1));wireRemove()};wireRemove()};
function wireRemove(){document.querySelectorAll("[data-remove]").forEach(n=>n.onclick=()=>{if(document.querySelectorAll("[data-row]").length>1)n.closest("[data-row]").remove()})}
async function generateSampling(){const c=state.detail.case;await api(`/api/v1/cases/${c.id}/sampling/generate`,{method:"POST",body:JSON.stringify({...identity(),expectedRevision:c.revision})});await openCase(c.id);toast("抽样方案已生成")}
function confirmSampling(){const c=state.detail.case;modal("抽样偏差说明与平衡核对",c.sampling.items.map(i=>`<div class="batch-row" data-sampling="${esc(i.lotId)}"><strong>${esc(i.lotCode)}</strong><small>计划 ${i.plannedCount} · 留样 ${i.reservedCount}</small>${fields([{name:"actual",label:"实际取样量",type:"number",value:i.plannedCount},{name:"reason",label:"偏差原因（实际量偏离计划时必填）",required:false}])}</div>`).join(""),async(_,form)=>{const actualCounts={},deviationReasons={};form.querySelectorAll("[data-sampling]").forEach(row=>{actualCounts[row.dataset.sampling]=+row.querySelector('[name="actual"]').value;const reason=row.querySelector('[name="reason"]').value.trim();if(reason)deviationReasons[row.dataset.sampling]=reason});await api(`/api/v1/cases/${c.id}/sampling/confirm`,{method:"POST",body:JSON.stringify({...identity(),expectedRevision:c.revision,actualCounts,deviationReasons})});await openCase(c.id);toast("数量平衡已确认并冻结")})}
$("#add-test").onclick=()=>{const selected=[...document.querySelectorAll("[data-missing]:checked")].map(n=>n.dataset.missing),all=(state.detail.testMatrix||[]).filter(x=>x.state==="missing").map(x=>`${x.lotId}|${x.testType}`),keys=selected.length?selected:all;if(!keys.length)return toast("没有待录入的初检缺项");const c=state.detail.case,cells=keys.map(k=>{const [lotId,testType]=k.split("|");return state.detail.testMatrix.find(x=>x.lotId===lotId&&x.testType===testType)});modal("检验矩阵批量录入",cells.map((cell,i)=>`<div class="batch-row" data-test="${i}"><strong>${esc(cell.lotCode)} · ${cell.testType==="germination"?"发芽活力":"污染筛查"}</strong>${fields([{name:"replicates",label:"各重复样本数（逗号分隔）",value:"25,25"},{name:"passed",label:"通过数量",type:"number",value:cell.testType==="germination"?45:49},{name:"contaminated",label:"污染数量",type:"number",value:cell.testType==="contamination"?1:0},{name:"threshold",label:"阈值（%）",type:"number",step:"0.1",value:cell.testType==="germination"?80:5}])}</div>`).join(""),async(_,form)=>{const items=cells.map((cell,i)=>{const row=form.querySelector(`[data-test="${i}"]`),reps=row.querySelector('[name="replicates"]').value.split(",").map(Number);return {lotId:cell.lotId,testType:cell.testType,replicateCounts:reps,testedCount:reps.reduce((a,b)=>a+b,0),passedCount:+row.querySelector('[name="passed"]').value,contaminatedCount:+row.querySelector('[name="contaminated"]').value,threshold:+row.querySelector('[name="threshold"]').value}});await api(`/api/v1/cases/${c.id}/tests/batch`,{method:"POST",body:JSON.stringify({...identity(),expectedRevision:c.revision,items})});await openCase(c.id);await loadCases();toast(`${items.length}项初检已原子录入`)})};
function assignFinding(id){const c=state.detail.case,f=c.findings.find(x=>x.id===id);modal("设置整改负责人和期限",fields([{name:"assignee",label:"整改负责人",value:f.assignee||$("#actor").value},{name:"dueAt",label:"截止时间",type:"datetime-local",value:f.dueAt?localValue(f.dueAt):localValue(Date.now()+7*86400000)}]),async fd=>{const d=Object.fromEntries(fd);await api(`/api/v1/cases/${c.id}/findings/${id}/assign`,{method:"POST",body:JSON.stringify({...identity(),expectedRevision:c.revision,assignee:d.assignee,dueAt:new Date(d.dueAt)})});await openCase(c.id);await loadCases();toast("整改责任与期限已保存")})}
function addEvidence(id){const c=state.detail.case;modal("追加处置证据",fields([{name:"description",label:"证据说明",type:"textarea"},{name:"content",label:"证据内容（仅保存摘要）",type:"textarea"}]),async fd=>{const d=Object.fromEntries(fd);await api(`/api/v1/cases/${c.id}/findings/${id}/evidence`,{method:"POST",body:JSON.stringify({...identity(),expectedRevision:c.revision,...d})});await openCase(c.id);toast("证据已追加到不可覆盖台账")})}
function recordRetest(id){const c=state.detail.case,f=c.findings.find(x=>x.id===id),source=c.tests.find(x=>x.id===f.sourceTestId);modal("记录同类型复验",fields([{name:"replicates",label:"各重复样本数（逗号分隔）",value:"25,25"},{name:"passed",label:"通过数量",type:"number",value:source.testType==="germination"?45:49},{name:"contaminated",label:"污染数量",type:"number",value:source.testType==="contamination"?1:0},{name:"threshold",label:"阈值（%）",type:"number",value:source.threshold}]),async fd=>{const d=Object.fromEntries(fd),reps=d.replicates.split(",").map(Number);await api(`/api/v1/cases/${c.id}/tests`,{method:"POST",body:JSON.stringify({...identity(),expectedRevision:c.revision,lotId:f.lotId,testType:source.testType,replicateCounts:reps,testedCount:reps.reduce((a,b)=>a+b,0),passedCount:+d.passed,contaminatedCount:+d.contaminated,threshold:+d.threshold,isRetest:true})});await openCase(c.id);toast("复验已记录")})}
function remediate(id){const c=state.detail.case,f=c.findings.find(x=>x.id===id),source=c.tests.find(x=>x.id===f.sourceTestId),retests=c.tests.filter(t=>t.isRetest&&t.result==="pass"&&t.lotId===f.lotId&&t.testType===source.testType);if(!f.evidenceLedger?.length)return toast("请先追加至少一条处置证据");if(!retests.length)return toast("请先记录同批次同类型且通过的复验");modal("提交整改与复验",fields([{name:"retestId",label:"关联通过复验",type:"select",options:retests.map(t=>[t.id,`${t.testType} · ${t.performedBy} · ${new Date(t.performedAt).toLocaleString()}`])}]),async fd=>{const d=Object.fromEntries(fd);await api(`/api/v1/cases/${c.id}/findings/${id}/remediate`,{method:"POST",body:JSON.stringify({...identity(),expectedRevision:c.revision,retestId:d.retestId})});await openCase(c.id);toast("整改已提交，等待独立复核")})}
async function closeFinding(id){const c=state.detail.case;await api(`/api/v1/cases/${c.id}/findings/${id}/close`,{method:"POST",body:JSON.stringify({...identity(),expectedRevision:c.revision})});await openCase(c.id);await loadCases();toast("发现项已独立关闭")}
$("#approve").onclick=async()=>{const c=state.detail.case;try{await api(`/api/v1/cases/${c.id}/approve`,{method:"POST",body:JSON.stringify({...identity(),expectedRevision:c.revision})});await openCase(c.id);await loadCases();toast("案卷已冻结并签发凭据")}catch(err){toast(err.message)}};
async function verifyCredential(kind,value){const q=new URLSearchParams({[kind]:String(value)}),x=await api(`/api/v1/certificates/verify?${q}`),box=$("#verify-result");box.innerHTML=`<div class="verification ${x.valid?"valid":"invalid"}"><strong>${esc(x.message)}</strong>${x.checks.map(c=>`<p>${c.passed?"✓":"×"} ${esc(c.label)}：${esc(c.message)}</p>`).join("")}${x.manifestSummary?`<details><summary>冻结清单业务摘要</summary><pre>${esc(JSON.stringify(x.manifestSummary,null,2))}</pre></details>`:""}</div>`;toast(x.valid?"凭据核验通过":"凭据核验未通过")}
$("#credential-search").onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));try{await verifyCredential(d.kind,d.value.trim())}catch(err){$("#verify-result").textContent=err.message;toast(err.message)}};
document.querySelectorAll(".filters button").forEach(n=>n.onclick=async()=>{document.querySelectorAll(".filters button").forEach(x=>x.classList.remove("active"));n.classList.add("active");state.status=n.dataset.status;await loadCases()});
$("#timeliness-filter").onchange=async e=>{state.timeliness=e.target.value;await loadCases()};$("#role").onchange=()=>state.detail&&renderDetail();
loadCases().catch(err=>toast(err.message));
